    - name: update Packages first
      apt:
        update_cache: true

    - name: install Dependencies
      apt:
        name: 
         - openjdk-11-jdk
         - wget
         - zip
         - python3-pip
         - python3-psycopg2
        state: present
        update_cache: true

    - name: Add PostgreSQL repository
      command: echo "deb http://apt.postgresql.org/pub/repos/apt/ lsb_release -cs-pgdg main" >> /etc/apt/sources.list.d/pgdg.list

    - name: Add key to apt
      apt_key:
       url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
       state: present

    - name: Install PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Install postgresql-contrib
      apt:
        name: postgresql-contrib
        state: present

    - name: Enable and start postgresql
      service:
          name: postgresql
          enabled: true
          state: started

    - name: Change PostgreSQL password for postgres user
      user:
        name: postgres
        password: "{{ Postgres_password }}"

    - name: Create the sonar user
      user:
        name: sonar
        comment: "SonarQube User"

    - name: Change line trust
      replace:
       path: /etc/postgresql/14/main/pg_hba.conf
       regexp:  "local   all             postgres                                peer"
       replace: "local   all             postgres                                trust"
    
    - name: Change line md5
      replace:
       path: /etc/postgresql/14/main/pg_hba.conf
       regexp:  "local   all             all                                     peer"
       replace: "local   all             all                                     md5"

       
    - name: Restart postgresql
      become: true
      service:
        name: postgresql
        state: restarted
        enabled: true
        
    - name: Create the database  
      postgresql_db:
       login_user: postgres
       login_password: "{{ Postgres_password }}"
       name: sonarqube 
       template: 'template0'
       state: present

    - name: Create sonar user, and grant access
      postgresql_user:
        db: sonarqube
        name: sonar
        password: "{{ Postgres_password }}"
        priv: ALL
        expires: infinity